DEEPICT_HOME = 'DEEPICT_HOME'
VERSION = '0'
#CRYOCARE_DEFAULT_VERSION = V0_1_1
DEEPICT = 'DeePiCt'
DEEPICT_ENV_NAME = '%s-%s' % (DEEPICT, VERSION)
DEEPICT_ENV_ACTIVATION = 'DEEPICT_ENV_ACTIVATION'
DEFAULT_ACTIVATION_CMD = 'conda activate %s' % DEEPICT_ENV_NAME
DEEPICT_CUDA_LIB = 'DEEPICT_CUDA_LIB'
